spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopappclothes"
    username: root
    password: 123456
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
#      ddl-auto: none
    show-sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: "sub"
cloudinary:
  cloud-name: "${CLOUDINARY_NAME:dinvsgjet}"
  api-key: "${CLOUDINARY_API_KEY:529488681841853}"
  api-secret: "${CLOUDINARY_API_SECRET:3MHUPMlnyEK_dU4EIRPp_GUGc5E}"
jwt:
  signerKey: "${JWT_SIGNER_KEY}"
  valid-duration: 86400
  refreshable-duration: 3000000
vnpay:
  tmn-code: "${VNP_TMNCODE}"
  hash-secret: "${VNP_HASHSECRET}"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/payments/vnpay/return"
  version: "2.1.0"
  command: "pay"
  curr-code: "VND"
  locale: "vn"
  timeout-minutes: 15
app:
  fontend-url: "${FRONTEND_URL:http://localhost:3000/payment-result}"